"""added last_modified to parties_attended table

Revision ID: 0476d3e436d4
Revises: ace40a01c380
Create Date: 2022-08-31 18:05:37.384131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0476d3e436d4"
down_revision = "ace40a01c380"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parties_attended", sa.Column("created_on", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "parties_attended", sa.Column("last_modified_on", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parties_attended", "last_modified_on")
    op.drop_column("parties_attended", "created_on")
    # ### end Alembic commands ###
