"""Unique constraint for party and user in parties attended

Revision ID: 1319c49d192e
Revises: ba5b4372c639
Create Date: 2022-12-26 16:58:06.327627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1319c49d192e'
down_revision = 'ba5b4372c639'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_table_party_user', 'parties_attended', ['party_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_table_party_user', 'parties_attended', type_='unique')
    # ### end Alembic commands ###
