"""Unique name for each team

Revision ID: 1dce40a9b7e6
Revises: 89b3ff58fa3d
Create Date: 2022-12-27 01:09:16.541135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1dce40a9b7e6"
down_revision = "89b3ff58fa3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_table_team_name", "teams", ["team_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_table_team_name", "teams", type_="unique")
    # ### end Alembic commands ###
