"""Create team user table

Revision ID: 212c0582bf6a
Revises: 5be41977eec9
Create Date: 2023-02-28 19:05:08.348487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "212c0582bf6a"
down_revision = "5be41977eec9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("subscribed", sa.Boolean(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("last_modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_team_user_id"), "team_user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_user_id"), table_name="team_user")
    op.drop_table("team_user")
    # ### end Alembic commands ###
