"""New enums for notifications

Revision ID: 5b2fc697ff0d
Revises: f4ed0b19238b
Create Date: 2023-03-03 20:42:19.994976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b2fc697ff0d"
down_revision = "f4ed0b19238b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("COMMIT")
    op.execute("ALTER TYPE notificationtypeenum ADD VALUE 'REQUEST_REJECTION'")
    op.execute("ALTER TYPE notificationtypeenum ADD VALUE 'UNSUBSCRIBE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
