"""assign permissions to roles

Revision ID: 5be41977eec9
Revises: 305570004339
Create Date: 2023-02-22 23:43:05.123656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5be41977eec9"
down_revision = "305570004339"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'create_admin'), "
        "(select id from roles where role = 'superuser'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'add_user_to_team'), "
        "(select id from roles where role = 'superuser'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'remove_user_from_team'), "
        "(select id from roles where role = 'superuser'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'send_email'), "
        "(select id from roles where role = 'superuser'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'create_party'), "
        "(select id from roles where role = 'superuser'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'add_user_to_team'), "
        "(select id from roles where role = 'admin'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'remove_user_from_team'), "
        "(select id from roles where role = 'admin'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'send_email'), "
        "(select id from roles where role = 'admin'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'create_party'), "
        "(select id from roles where role = 'admin'));"
    )
    op.execute(
        "insert into permission_role values (DEFAULT, "
        "(select id from permissions where permission = 'create_party'), "
        "(select id from roles where role = 'regular'));"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
