"""Create permissions_role table

Revision ID: 683567424c0f
Revises: 89b9a478c657
Create Date: 2023-02-22 22:58:59.644689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "683567424c0f"
down_revision = "89b9a478c657"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_role_id"), "permission_role", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permission_role_id"), table_name="permission_role")
    op.drop_table("permission_role")
    # ### end Alembic commands ###
