"""Linked teams table with user table

Revision ID: 89b3ff58fa3d
Revises: 99ef1b644cec
Create Date: 2022-12-27 00:49:38.206507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89b3ff58fa3d"
down_revision = "99ef1b644cec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account_user", sa.Column("team_id", sa.Integer(), nullable=True))
    sa.ForeignKeyConstraint(
        ["team_id"],
        ["teams.id"],
    ),
    op.drop_column("account_user", "team")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_user",
        sa.Column("team", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "account_user", type_="foreignkey")
    op.drop_column("account_user", "team_id")
    # ### end Alembic commands ###
