"""Create roles table

Revision ID: 89b9a478c657
Revises: 0b5c7aaa5e34
Create Date: 2023-02-22 22:56:17.612531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89b9a478c657"
down_revision = "0b5c7aaa5e34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
