"""Created teams table

Revision ID: 99ef1b644cec
Revises: 1319c49d192e
Create Date: 2022-12-26 17:49:39.985799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99ef1b644cec"
down_revision = "1319c49d192e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("last_modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
