"""Not null constraint in team user table

Revision ID: ab6951e5964a
Revises: 164578622e16
Create Date: 2023-02-28 19:33:55.747785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab6951e5964a"
down_revision = "164578622e16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_user", "requested_by_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("team_user", "team_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("team_user", "team_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "team_user", "requested_by_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
