"""added last_modified to party table

Revision ID: ace40a01c380
Revises: 7b1e0a6b5723
Create Date: 2022-08-30 11:47:33.910512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ace40a01c380"
down_revision = "7b1e0a6b5723"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("party", sa.Column("last_modified_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("party", "last_modified_on")
    # ### end Alembic commands ###
