"""Added type_id in notifications table

Revision ID: b8952cebd479
Revises: c53031720030
Create Date: 2023-03-03 01:44:36.987304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8952cebd479"
down_revision = "c53031720030"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("type_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "type_id")
    # ### end Alembic commands ###
