"""Setting defaults for ratings in party

Revision ID: ba5b4372c639
Revises: 83e536370a77
Create Date: 2022-12-26 02:00:21.039051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba5b4372c639"
down_revision = "83e536370a77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("party", "ratings", default=0.0)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
