"""Create Party table

Revision ID: c7e50541938c
Revises: 884f01064c48
Create Date: 2022-08-25 03:37:53.863017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7e50541938c"
down_revision = "884f01064c48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "party",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("proposed_date", sa.DateTime(), nullable=False),
        sa.Column("guests_invited", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("party_date", sa.DateTime(), nullable=True),
        sa.Column("party_place", sa.String(), nullable=True),
        sa.Column("ratings", sa.Float(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_party_id"), "party", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_party_id"), table_name="party")
    op.drop_table("party")
    # ### end Alembic commands ###
