"""clear permission roles table

Revision ID: e2af834ca291
Revises: 872cf33ae99f
Create Date: 2023-03-02 01:08:39.587984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2af834ca291"
down_revision = "872cf33ae99f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_permission_role_id", table_name="permission_role")
    op.drop_table("permission_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_role",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name="permission_role_permission_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name="permission_role_role_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="permission_role_pkey"),
    )
    op.create_index("ix_permission_role_id", "permission_role", ["id"], unique=False)
    # ### end Alembic commands ###
