"""Create parties_due table

Revision ID: eabce295344c
Revises: c7e50541938c
Create Date: 2022-08-25 03:40:06.306832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eabce295344c"
down_revision = "c7e50541938c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parties_due",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("parties_due", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parties_due_id"), "parties_due", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parties_due_id"), table_name="parties_due")
    op.drop_table("parties_due")
    # ### end Alembic commands ###
