"""Team and DOJ columns addition in account user

Revision ID: eaf6e1fb3ab5
Revises: 0476d3e436d4
Create Date: 2022-10-27 23:28:11.603106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf6e1fb3ab5'
down_revision = '0476d3e436d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parties_due_id', table_name='parties_due')
    op.drop_table('parties_due')
    op.add_column('account_user', sa.Column('team', sa.String(), nullable=True))
    op.add_column('account_user', sa.Column('date_of_joining', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_user', 'date_of_joining')
    op.drop_column('account_user', 'team')
    op.create_table('parties_due',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parties_due', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], name='parties_due_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parties_due_pkey')
    )
    op.create_index('ix_parties_due_id', 'parties_due', ['id'], unique=False)
    # ### end Alembic commands ###
