"""unique constraint in team_user

Revision ID: ee3ddaef8ae0
Revises: ab6951e5964a
Create Date: 2023-03-01 19:43:39.273049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee3ddaef8ae0"
down_revision = "ab6951e5964a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_user_team_uc", "team_user", ["user_id", "team_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_team_uc", "team_user", type_="unique")
    # ### end Alembic commands ###
