"""unique constraint in notifications table

Revision ID: f4ed0b19238b
Revises: b8952cebd479
Create Date: 2023-03-03 01:48:10.492614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4ed0b19238b"
down_revision = "b8952cebd479"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_user_type_id_type_uc", "notifications", ["user_id", "type_id", "type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_type_id_type_uc", "notifications", type_="unique")
    # ### end Alembic commands ###
