name: test develop merge run

on:
  push:
    branches: develop
    
jobs: 
  mergeDevelop:
    name: reading github.event context
    runs-on: ubuntu-latest
    steps:
      - name: head_ref
        run: echo "${{ github.head_ref }}"
      
      - name: composing commit messages
        run: |
            echo "Commit Message: ${{ github.event.commits }}"
            commit_messages=''
            for commit in "${{ github.event.commits }}"; do
              echo "Commit Message: $commit.message"
              commit_messages+="$commit.message\n"
            done
            #echo "MY_ENV_VARIABLE=$commit_messages" >> $GITHUB_ENV
        
