on:
  push:
    branches:
      - develop
    
jobs:
  commitToGit:
    name: commit to git
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: write
    steps:
      - run: |
          github_token=${{ secrets.TOKEN_GITHUB }}
          curl -H "Authorization: Bearer $github_token" --location --request PATCH 'https://api.github.com/repos/hark444/party_project/actions/variables/LAST_STAGE_DEPLOYMENT' --header 'Accept: application/vnd.github.v3+json' --header 'Content-Type: application/json' --data '{
          "name": "LAST_STAGE_DEPLOYMENT",
          "value": "PPDEV-009"
          }'
