on:
  push:
    branches:
      - develop
    
jobs:
  commitToGit:
    name: commit to git
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - run: |
          curl --location --request PATCH 'https://api.github.com/repos/hark444/party_project/actions/variables/LAST_STAGE_DEPLOYMENT' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Content-Type: application/json' \
          --data '{
              "name": "LAST_STAGE_DEPLOYMENT",
              "value": "PPDEV-009"
          }'
