on:
  push:
    branches:
      - develop
    
jobs:
  commitToGit:
    name: commit to git
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "creating test.txt file"
          touch test.csv
          current_date=$(date)
          contents_to_append="$GITHUB_REF, test_commit_message, $current_date"
          echo contents_to_append >> test.csv
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding text.txt
          create_branch: true
          branch: test/1a
        
