on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the env variables
        run: env
        
      - name: run on develop
        run: echo "Running on ${{ vars.LAST_STAGE_DEPLOYMENT }}"
        
      - name: Set Environment Variable
        run: echo 'PPDEV-111' >> $vars.LAST_STAGE_DEPLOYMENT
        
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: listing all files
        run: |
          pwd
          ls -a
        
        
#       - name: setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' # install the python version needed
        
#       - name: write to file
#         run: python .github/workflows/write_to_file.py PPDEV-007
        
#       - name: reading file after edit
#         run: |
#           cat .github/workflows/foo.txt
      
      - name: "Set latest tag"
#         run: git tag | sort --version-sort | tail -n1
        run: echo "latest_tag=$(git tag | sort --version-sort | tail -n1)" >> $GITHUB_ENV
      
      - name: "checking out git commands"
        run: |
          git status
          git branch
          git tag | sort --version-sort | tail -n1

      - name: "Tag Docker image as latest"
        run: echo "Latest tag is ${{ env.latest_tag }}"
          
          
#       - name: Persist as GitHub Variable
#         run: echo "MY_STAGE_VARIABLE=${{ env.MY_STAGE_VARIABLE }}" >> $GITHUB_ENV
