on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the env variables
        run: env
        
      - name: run on develop
        run: echo "Running on ${{ secrets.LAST_STAGE_DEPLOYMENT_BRANCH }}"
        
      - name: github events
        run: echo ${{ toJSON(github.event) }}
