on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#         with:
#           ref: PPDEV-007
          
#       - name: Set Variable
#         run: echo "LAST_STAGE_DEPLOYMENT_BRANCH=PDEV-007" >> $GITHUB_ENV

      - name: Get all the env variables
        run: env
        
      - name: run on develop
        run: echo "Running on ${{ secrets.LAST_STAGE_DEPLOYMENT_BRANCH }}"
        
      - name: github events
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
