on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the env variables
        run: env
        
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: "checking out git commands"
        run: |
          git fetch
          echo "latest_tag=$(git tag | sort --version-sort | tail -n1)" >> $GITHUB_ENV
      
      - name: "Getting the sliced string"
        run: |
          echo "Latest tag is ${{ env.latest_tag }}"
          echo "latest_release_branch"="${{ env.latest_tag }} | cut -c 2-" >> $GITHUB_ENV
          
      - name: "echo the sliced string"
        run: |
          echo "latest release branch is: ${{ env.latest_release_branch }}"
        
