on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the env variables
        run: env
        
      - name: run on develop
        run: echo "Running on ${{ vars.LAST_STAGE_DEPLOYMENT }}"
        
      - name: Set Environment Variable
        run: echo 'PPDEV-111' >> $vars.LAST_STAGE_DEPLOYMENT
        
      - name: Make hidden envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456abcdef"
          file_name: .env
        
      - name: Make envfile
        run: |
          touch foos.txt
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> foos.txt
          echo API_KEY=${{ secrets.API_KEY }} >> foos.txt
          cat foos.txt
        
#       - name: "Set latest tag"
#         id: set-latest-tag
# #         run: git tag | sort --version-sort | tail -n1
#         run: echo "latest_tag=$(git tag | sort --version-sort | tail -n1)" >> $GITHUB_ENV

#       - name: "Tag Docker image as latest"
#         id: tag-as-latest
#         if: ${{ github.ref_name == env.latest_tag }}
#         run: |
          
          
#       - name: Persist as GitHub Variable
#         run: echo "MY_STAGE_VARIABLE=${{ env.MY_STAGE_VARIABLE }}" >> $GITHUB_ENV
