on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the env variables
        run: env
        
      - name: run on develop
        run: echo "Running on ${{ vars.LAST_STAGE_DEPLOYMENT }}"
        
      - name: Set Environment Variable
        run: echo 'PPDEV-111' >> $vars.LAST_STAGE_DEPLOYMENT
        
      - name: write to file
        run: python /.github/workflows/write_to_file.py PPDEV-007
      
#       - name: "Set latest tag"
#         id: set-latest-tag
# #         run: git tag | sort --version-sort | tail -n1
#         run: echo "latest_tag=$(git tag | sort --version-sort | tail -n1)" >> $GITHUB_ENV

#       - name: "Tag Docker image as latest"
#         id: tag-as-latest
#         if: ${{ github.ref_name == env.latest_tag }}
#         run: |
          
          
#       - name: Persist as GitHub Variable
#         run: echo "MY_STAGE_VARIABLE=${{ env.MY_STAGE_VARIABLE }}" >> $GITHUB_ENV
