on:
  schedule:
    - cron: '28 * * * *' # Executes at 1 PM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: PPDEV-007

      - name: Run on Specific Branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running on the main branch"
        
      - name: run on develop
        run: echo "Running on ref=${GITHUB_REF}"
