on:
  schedule:
    - cron: '0-59/10 * * * *' # Executes at 1 PM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the env variables
        run: env
        
      - name: run on develop
        run: echo "Running on ${{ vars.LAST_STAGE_DEPLOYMENT }}"
        
      - name: Set Environment Variable
        run: echo 'PPDEV-111' >> $vars.LAST_STAGE_DEPLOYMENT
          
          
#       - name: Persist as GitHub Variable
#         run: echo "MY_STAGE_VARIABLE=${{ env.MY_STAGE_VARIABLE }}" >> $GITHUB_ENV
