name: Send Email on Develop Push

on:
  push:
    branches:
      - develop

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          
          server_address: smtp.gmail.com
          server_port: 465
          username: hkeshwani78@gmail.com
          password: hvekpqahusdjycql
          
          subject: Github Actions job result
          to: hark44@yopmail.com
          from: Email Test
          body: Build job of ${{github.repository}} completed successfully!
          html_body: This is a test HTML body
