on:
  push:
    branches:
      - develop
#   schedule:
#     - cron: '0-59/6 * * * *' # Executes at 1 PM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
    
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
